[package]
name = "oddity-video"
version = "0.1.0"
authors = ["Oddity.ai Developers <hello@oddity.ai>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
tracing = "0.1"
ffmpeg-next = "4.4"
url = "2"
ndarray = { version = "0.15", optional = true }